spring.application.name=notification-service
server.port=8084

# Eureka Client Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# RabbitMQ Config
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Email Configuration
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=**Enter the email here**
spring.mail.password=**Enter the password here**
spring.mail.from=${SMTP_FROM:${spring.mail.username}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator configuration for health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
